[package]
name = "walletcryptography"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitive-types="0.12.1"
hex="0.4.3"
secp256k1="0.26.0"
rand="0.8.5"
